---
# tasks file for strongswan
- name: debug
  debug:
    var: compile

- include: debian.yml
  when:
    - ansible_os_family == "Debian"
    - not compile
- include: redhat.yml
  when:
    - ansible_os_family == "RedHat"
    - not compile
- include: arch.yml
  when:
    - ansible_os_family == "Archlinux"
    - not compile

- include: compile-debian.yml
  when:
    - compile

- include: config.yml
- include: service.yml
- include: firewall.yml