---
# Redhat-specific task file for strongswan

- include_vars: redhat.yml

- name:  redhat | Install strongSwan
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    "{{ strongswan_packages }}"
