---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
#  - name: instance-1
  - name: ha-1
    groups:
      - ha
  - name: ha-2
    groups:
      - ha
provisioner:
  name: ansible
  options:
    diff: True
    v: True
  playbooks:
    create: create.yml
    prepare: prepare.yml
    destroy: destroy.yml
scenario:
  name: default
verifier:
  name: goss
