---
- name: run the main role
  hosts: ha
  become: true
  become_method: su
  become_user: root
  vars:
    compile: true
  roles:
    - {role: ansible-strongswan}
  post_tasks:
    - name: create script 
      copy:
        content: |
          #!/bin/bash
          TYPE=$1
          NAME=$2
          STATE=$3
          case $STATE in
                  "MASTER") /usr/sbin/service strongswan start
                            ;;
                  "BACKUP") /usr/sbin/service strongswan stop
                            ;;
                  "FAULT")  /usr/sbin/service strongswan stop
                            exit 0
                            ;;
                  *)        /sbin/logger "ipsec unknown state"
                            exit 1
                            ;;
          esac
        dest: /usr/local/sbin/notify-keepalived.sh
        mode: '0500'

- name: run the main role
  hosts: instance-1
  become: true
  become_method: su
  become_user: root
  roles:
    - {role: ansible-strongswan}
- name: KEEPALIVE_HAPROXY_IP_1_NODE_1
  become: true
  become_user: root
  become_method: su
  hosts: ha[0]
  roles:
    - role: entercloudsuite.keepalived
      keepalived_options:
        - name: log-detail

      keepalived_vrrp_instances:
        VI_1:
          interface: ens3
          state: MASTER
          priority: 110
          virtual_router_id: 71
          notify: /usr/local/sbin/notify-keepalived.sh

          authentication:
            auth_type: PASS
            auth_pass: 'pass123!'

          virtual_ipaddresses:
            - '10.2.255.1 dev ens3 label ens3:1'

          track_scripts:
            - chk_haproxy

- name: KEEPALIVE_HAPROXY_IP_1_NODE_2
  become: true
  become_user: root
  become_method: su
  hosts: ha[1]
  roles:
    - role: entercloudsuite.keepalived
      keepalived_options:
        - name: log-detail

      keepalived_vrrp_instances:
        VI_1:
          interface: ens3
          state: BACKUP
          priority: 100
          virtual_router_id: 71
          notify: /usr/local/sbin/notify-keepalived.sh

          authentication:
            auth_type: PASS
            auth_pass: 'pass123!'

          virtual_ipaddresses:
            - '10.2.255.1 dev ens3 label ens3:1'

          track_scripts:
            - chk_haproxy