---

- hosts: all
  gather_facts: False
  tasks:
  - name: install ansible prerequisite (python)
    raw: echo "nameserver 1.1.1.1" > /etc/resolv.conf

  - name: install ansible prerequisite (python)
    raw: test -e /usr/bin/python || ( apt update -y && apt install python-minimal -y )

  - name: install apparmor
    package: name=apparmor
  - name: install pkg-config
    package: name=pkg-config
